/* tslint:disable */
/* eslint-disable */
/**
 * microcms-sdk-generator-demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Articles,
    ArticlesFromJSON,
    ArticlesFromJSONTyped,
    ArticlesToJSON,
} from './';

/**
 * 
 * @export
 * @interface ArticlesList
 */
export interface ArticlesList {
    /**
     * 
     * @type {Array<Articles>}
     * @memberof ArticlesList
     */
    contents: Array<Articles>;
    /**
     * 
     * @type {number}
     * @memberof ArticlesList
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof ArticlesList
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof ArticlesList
     */
    totalCount: number;
}

export function ArticlesListFromJSON(json: any): ArticlesList {
    return ArticlesListFromJSONTyped(json, false);
}

export function ArticlesListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticlesList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contents': ((json['contents'] as Array<any>).map(ArticlesFromJSON)),
        'limit': json['limit'],
        'offset': json['offset'],
        'totalCount': json['totalCount'],
    };
}

export function ArticlesListToJSON(value?: ArticlesList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contents': ((value.contents as Array<any>).map(ArticlesToJSON)),
        'limit': value.limit,
        'offset': value.offset,
        'totalCount': value.totalCount,
    };
}


