/* tslint:disable */
/* eslint-disable */
/**
 * microcms-sdk-generator-demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommonUpdateResult
 */
export interface CommonUpdateResult {
    /**
     * 
     * @type {string}
     * @memberof CommonUpdateResult
     */
    id: string;
}

export function CommonUpdateResultFromJSON(json: any): CommonUpdateResult {
    return CommonUpdateResultFromJSONTyped(json, false);
}

export function CommonUpdateResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonUpdateResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function CommonUpdateResultToJSON(value?: CommonUpdateResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


