/* tslint:disable */
/* eslint-disable */
/**
 * microcms-sdk-generator-demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Articles,
    ArticlesFromJSON,
    ArticlesFromJSONTyped,
    ArticlesToJSON,
} from './';

/**
 * 
 * @export
 * @interface Setting
 */
export interface Setting {
    /**
     * 1ページあたりの記事数
     * @type {number}
     * @memberof Setting
     */
    articlesPerPage: number;
    /**
     * 
     * @type {Date}
     * @memberof Setting
     */
    createdAt: Date;
    /**
     * 特集記事
     * @type {Array<Articles>}
     * @memberof Setting
     */
    featuredArticles: Array<Articles>;
    /**
     * 
     * @type {string}
     * @memberof Setting
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof Setting
     */
    publishedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Setting
     */
    revisedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Setting
     */
    updatedAt: Date;
}

export function SettingFromJSON(json: any): Setting {
    return SettingFromJSONTyped(json, false);
}

export function SettingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Setting {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'articlesPerPage': json['articlesPerPage'],
        'createdAt': (new Date(json['createdAt'])),
        'featuredArticles': ((json['featuredArticles'] as Array<any>).map(ArticlesFromJSON)),
        'id': json['id'],
        'publishedAt': (new Date(json['publishedAt'])),
        'revisedAt': (new Date(json['revisedAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function SettingToJSON(value?: Setting | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'articlesPerPage': value.articlesPerPage,
        'createdAt': (value.createdAt.toISOString()),
        'featuredArticles': ((value.featuredArticles as Array<any>).map(ArticlesToJSON)),
        'id': value.id,
        'publishedAt': (value.publishedAt.toISOString()),
        'revisedAt': (value.revisedAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
    };
}


