/* tslint:disable */
/* eslint-disable */
/**
 * microcms-sdk-generator-demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Setting,
    SettingFromJSON,
    SettingFromJSONTyped,
    SettingToJSON,
} from './';

/**
 * 
 * @export
 * @interface SettingList
 */
export interface SettingList {
    /**
     * 
     * @type {Array<Setting>}
     * @memberof SettingList
     */
    contents: Array<Setting>;
    /**
     * 
     * @type {number}
     * @memberof SettingList
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof SettingList
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof SettingList
     */
    totalCount: number;
}

export function SettingListFromJSON(json: any): SettingList {
    return SettingListFromJSONTyped(json, false);
}

export function SettingListFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contents': ((json['contents'] as Array<any>).map(SettingFromJSON)),
        'limit': json['limit'],
        'offset': json['offset'],
        'totalCount': json['totalCount'],
    };
}

export function SettingListToJSON(value?: SettingList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contents': ((value.contents as Array<any>).map(SettingToJSON)),
        'limit': value.limit,
        'offset': value.offset,
        'totalCount': value.totalCount,
    };
}


