/* tslint:disable */
/* eslint-disable */
/**
 * microcms-sdk-generator-demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * アイコン
 * @export
 * @interface UsersIcon
 */
export interface UsersIcon {
    /**
     * 
     * @type {number}
     * @memberof UsersIcon
     */
    height?: number;
    /**
     * 
     * @type {string}
     * @memberof UsersIcon
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof UsersIcon
     */
    width?: number;
}

export function UsersIconFromJSON(json: any): UsersIcon {
    return UsersIconFromJSONTyped(json, false);
}

export function UsersIconFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersIcon {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'height': !exists(json, 'height') ? undefined : json['height'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'width': !exists(json, 'width') ? undefined : json['width'],
    };
}

export function UsersIconToJSON(value?: UsersIcon | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'height': value.height,
        'url': value.url,
        'width': value.width,
    };
}


