/* tslint:disable */
/* eslint-disable */
/**
 * microcms-sdk-generator-demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Users,
    UsersFromJSON,
    UsersFromJSONTyped,
    UsersToJSON,
} from './';

/**
 * 
 * @export
 * @interface UsersList
 */
export interface UsersList {
    /**
     * 
     * @type {Array<Users>}
     * @memberof UsersList
     */
    contents: Array<Users>;
    /**
     * 
     * @type {number}
     * @memberof UsersList
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof UsersList
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof UsersList
     */
    totalCount: number;
}

export function UsersListFromJSON(json: any): UsersList {
    return UsersListFromJSONTyped(json, false);
}

export function UsersListFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contents': ((json['contents'] as Array<any>).map(UsersFromJSON)),
        'limit': json['limit'],
        'offset': json['offset'],
        'totalCount': json['totalCount'],
    };
}

export function UsersListToJSON(value?: UsersList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contents': ((value.contents as Array<any>).map(UsersToJSON)),
        'limit': value.limit,
        'offset': value.offset,
        'totalCount': value.totalCount,
    };
}


